# Generated by Django 3.1 on 2020-11-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_time_management', '0002_auto_20201028_2211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]