# Generated by Django 3.1 on 2020-11-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_time_management', '0004_auto_20201122_2023'),
    ]

    operations = [
    ]