# Generated by Django 3.1 on 2020-11-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_time_management', '0005_auto_20201122_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtime',
            name='event_time',
            field=models.IntegerField(default=0, help_text='event time'),
        ),
    ]
