# Generated by Django 3.1 on 2020-11-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_time_management', '0007_auto_20201122_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtime',
            name='wake_event_time',
            field=models.IntegerField(default=0, help_text='wake event time'),
        ),
    ]
