# Generated by Django 3.1 on 2020-11-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_time_management', '0008_eventtime_wake_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtime',
            name='sleep_data',
            field=models.TextField(default='', help_text='sleep data'),
        ),
    ]
