# Generated by Django 3.1 on 2020-12-15 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sleep_time_management', '0010_auto_20201214_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtime',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='date eventtime'),
        ),
        migrations.AlterField(
            model_name='eventtime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
