# Generated by Django 3.1 on 2020-11-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_gender')
    ]

    operations = [
    ]
