# Generated by Django 3.1 on 2020-12-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_merge_20201109_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_span',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='average',
            field=models.CharField(default='', help_text='average sleep time', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
    ]
